import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Roboto } from "next/font/google";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
const roboto = Roboto({ subsets: ["latin"], weight: ["400","700"], variable: "--font-roboto" });

export const metadata: Metadata = {
    title: "ARC Restaurant Supply",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className={roboto.variable}>
            <body
                className={`font-sans ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
        <Header />
        <main className="min-h-screen bg-gray-100">{children}</main>
        </body>
        </html>
    );
}
